#all: simplest_ffmpeg_player.c
#	cc simplest_ffmpeg_player.c -lavformat -lavcodec -lavutil -lswscale -lswresample -lm -lz -lpthread -lbz2 -lrt `sdl-config --cflags --libs`
all: tutorial1.c
	cc tutorial1.c -lavformat -lavcodec -lavutil -lswscale -lswresample -lm -lz -lpthread -lbz2 -lrt `sdl-config --cflags --libs`
#all: test_ffmpeg.c
#	cc test_ffmpeg.c -lavformat -lavcodec -lavutil -lswscale -lswresample -lm -lz -lSDL -lpthread -lbz2 -lrt
clean:
	rm a.out
